### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by yahengmath** [kevinlb1/CATS#3]
Hi,

Can you give some examples of how to generate instances? I am trying both on Windows and Linux, but I can not make it work. 

Thanks,
Yaheng

**Comment by lythronaxargestes** [comment]
Hi Yaheng,

What challenges are you encountering? 
A minimal command to generate instances would be in the form of
`./cats -d [distribution] -goods [goods] -bids [bids]`
e.g.
`./cats -d matching -goods 32 -bids 128`

**Comment by yahengmath** [comment]
In fact, I am trying as your examples.

But on windows, the software is running with errors like "cygstdc ++-6.dll" not found, etc... On Linux, there is no cats file (except the software) for using.

Thanks,
Yaheng

**Comment by lythronaxargestes** [comment]
On Windows, please try installing [Cygwin](https://www.cygwin.com/).

On Linux, please try running `make`.

**Comment by yahengmath** [comment]
On Linux, I am trying with the command under the folder of CATS: $ make -d paths -goods 32 -bids 128, it showed error as 'make: invalid option --'g'.

Thanks,
Yaheng

**Comment by lythronaxargestes** [comment]
Please try running just `make`. Those arguments are for `./cats`.

**Comment by yahengmath** [comment]
If only run with make, where can I set the bids information? Very sorry for these stupid questions, I am new for Linux.

Thanks,
Yaheng

**Comment by lythronaxargestes** [comment]
You need to compile the `cats` executable first before you can run it. This is done by running `make`. If it compiles successfully, then you can call `./cats [args]`.
